spring.application.name=build-compiler
# Ensure Swagger uses HTTPS for API calls
springdoc.api-docs.url=https://compiler-for-devconnect-production.up.railway.app/v3/api-docs
springdoc.swagger-ui.url=https://compiler-for-devconnect-production.up.railway.app/swagger-ui.html